language: node_js
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export NODE_OPTIONS=--max_old_space_size=4096

jobs:
  include:
    - stage: release
      script: yarn install
      before_deploy:
        - cd dist
      deploy:
        provider: npm
    

#jobs:
#  include:
#    - stage: build
#      script:
#        - yarn install
#    - stage: release
#      node_js: lts/*
#      script:
#        - npm run semantic-release
